services:
  - type: web
    name: talentsqr
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM
        sync: false
